version: 1.40.{build}
pull_requests:
  do_not_increment_build_number: true
skip_non_tags: true
shallow_clone: true
environment:
  VCVER: 14.0
  QTCOMPILER: msvc2015
  ARCH: x86
  CMakeArgs: "-DLSLAPPS_LabRecorder=1"
install:
- cmd: >-
    appveyor DownloadFile https://github.com/ninja-build/ninja/releases/download/v1.8.2/ninja-win.zip -FileName ninja.zip

    7z x ninja.zip -oC:\projects\deps\ninja > nul

    set PATH=C:\projects\deps\ninja;%PATH%

    ninja --version
build_script:
- cmd: >-
    call "C:\Program Files (x86)\Microsoft Visual Studio %VCVER%\VC\vcvarsall.bat" %ARCH%

    cd build

    cmake -G Ninja -DQt5_DIR=C:/Qt/5.9.1/%QTCOMPILER%/lib/cmake/Qt5 -DBOOST_ROOT=C:/Libraries/boost_1_63_0 -DCMAKE_BUILD_TYPE=Release -DCMAKE_INSTALL_PREFIX=install %CMakeArgs% ../

    cmake --build . --config Release --target LSLPACKAGE
artifacts:
- path: build/lslinstall
  name: lsl_Win32_$(APPVEYOR_BUILD_VERSION)_${APPVEYOR_REPO_COMMIT}
deploy:
- provider: BinTray
  username: tstenner
  api_key:
    secure: zcgGai0IfIlkwU5IXEvoJ/Kr+w2DbKIBJr/677Q52BPwUT0aFWSvJuZp2obpY3u5
  subject: tstenner
  repo: labstreaminglayer
  package: LSL
  publish: false
  explode: false
  override: false
